name: Test and publish

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  test-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.17.1

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm -r --filter '!paralax-plugin' test --if-present

      - name: Build packages
        run: pnpm -r build

      - name: Configure GitHub Packages registry
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          registry-url: https://npm.pkg.github.com

      - name: Publish packages
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Ensure maintainers have configured .npmrc or rely on setup-node registry configuration
          # so pnpm publish targets https://npm.pkg.github.com
          pnpm -r publish --no-git-checks --access restricted
